/**
 * Curated city list for Prayer Settings city picker.
 * Country names are aligned with Aladhan API expectations.
 */

export interface CityEntry {
  name: string;
  country: string;
}

export const CITIES: CityEntry[] = [
  // A
  { name: 'Abu Dhabi', country: 'United Arab Emirates' },
  { name: 'Accra', country: 'Ghana' },
  { name: 'Addis Ababa', country: 'Ethiopia' },
  { name: 'Adelaide', country: 'Australia' },
  { name: 'Algiers', country: 'Algeria' },
  { name: 'Almaty', country: 'Kazakhstan' },
  { name: 'Amman', country: 'Jordan' },
  { name: 'Amsterdam', country: 'Netherlands' },
  { name: 'Ankara', country: 'Turkey' },
  { name: 'Astana', country: 'Kazakhstan' },
  { name: 'Athens', country: 'Greece' },
  { name: 'Auckland', country: 'New Zealand' },
  { name: 'Austin', country: 'United States' },
  // B
  { name: 'Baghdad', country: 'Iraq' },
  { name: 'Baku', country: 'Azerbaijan' },
  { name: 'Bali', country: 'Indonesia' },
  { name: 'Bamako', country: 'Mali' },
  { name: 'Bandung', country: 'Indonesia' },
  { name: 'Bangkok', country: 'Thailand' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Basra', country: 'Iraq' },
  { name: 'Beijing', country: 'China' },
  { name: 'Beirut', country: 'Lebanon' },
  { name: 'Belgrade', country: 'Serbia' },
  { name: 'Berlin', country: 'Germany' },
  { name: 'Birmingham', country: 'United Kingdom' },
  { name: 'Bishkek', country: 'Kyrgyzstan' },
  { name: 'Brisbane', country: 'Australia' },
  { name: 'Brussels', country: 'Belgium' },
  { name: 'Bucharest', country: 'Romania' },
  { name: 'Budapest', country: 'Hungary' },
  { name: 'Buenos Aires', country: 'Argentina' },
  // C
  { name: 'Cairo', country: 'Egypt' },
  { name: 'Calgary', country: 'Canada' },
  { name: 'Canberra', country: 'Australia' },
  { name: 'Casablanca', country: 'Morocco' },
  { name: 'Chennai', country: 'India' },
  { name: 'Chicago', country: 'United States' },
  { name: 'Chittagong', country: 'Bangladesh' },
  { name: 'Cologne', country: 'Germany' },
  { name: 'Colombo', country: 'Sri Lanka' },
  { name: 'Copenhagen', country: 'Denmark' },
  // D
  { name: 'Dakar', country: 'Senegal' },
  { name: 'Dallas', country: 'United States' },
  { name: 'Damascus', country: 'Syria' },
  { name: 'Dar es Salaam', country: 'Tanzania' },
  { name: 'Delhi', country: 'India' },
  { name: 'Denver', country: 'United States' },
  { name: 'Detroit', country: 'United States' },
  { name: 'Dhaka', country: 'Bangladesh' },
  { name: 'Doha', country: 'Qatar' },
  { name: 'Dubai', country: 'United Arab Emirates' },
  { name: 'Dublin', country: 'Ireland' },
  { name: 'Dushanbe', country: 'Tajikistan' },
  // E
  { name: 'Edmonton', country: 'Canada' },
  // F
  { name: 'Faisalabad', country: 'Pakistan' },
  { name: 'Fez', country: 'Morocco' },
  { name: 'Frankfurt', country: 'Germany' },
  { name: 'Freetown', country: 'Sierra Leone' },
  { name: 'Fresno', country: 'United States' },
  // G
  { name: 'Gaza', country: 'Palestine' },
  { name: 'George Town', country: 'Malaysia' },
  { name: 'Giza', country: 'Egypt' },
  { name: 'Guadalajara', country: 'Mexico' },
  { name: 'Guangzhou', country: 'China' },
  // H
  { name: 'Hamburg', country: 'Germany' },
  { name: 'Hangzhou', country: 'China' },
  { name: 'Hanoi', country: 'Vietnam' },
  { name: 'Hargeisa', country: 'Somalia' },
  { name: 'Houston', country: 'United States' },
  { name: 'Hyderabad', country: 'India' },
  // I
  { name: 'Ibadan', country: 'Nigeria' },
  { name: 'Indianapolis', country: 'United States' },
  { name: 'Indore', country: 'India' },
  { name: 'Isfahan', country: 'Iran' },
  { name: 'Islamabad', country: 'Pakistan' },
  { name: 'Istanbul', country: 'Turkey' },
  { name: 'Izmir', country: 'Turkey' },
  // J
  { name: 'Jaipur', country: 'India' },
  { name: 'Jakarta', country: 'Indonesia' },
  { name: 'Jeddah', country: 'Saudi Arabia' },
  { name: 'Jerusalem', country: 'Palestine' },
  { name: 'Johannesburg', country: 'South Africa' },
  { name: 'Johor Bahru', country: 'Malaysia' },
  // K
  { name: 'Kabul', country: 'Afghanistan' },
  { name: 'Kampala', country: 'Uganda' },
  { name: 'Kano', country: 'Nigeria' },
  { name: 'Kansas City', country: 'United States' },
  { name: 'Karachi', country: 'Pakistan' },
  { name: 'Karbala', country: 'Iraq' },
  { name: 'Kathmandu', country: 'Nepal' },
  { name: 'Khartoum', country: 'Sudan' },
  { name: 'Kiev', country: 'Ukraine' },
  { name: 'Kolkata', country: 'India' },
  { name: 'Kuala Lumpur', country: 'Malaysia' },
  { name: 'Kuwait City', country: 'Kuwait' },
  // L
  { name: 'Lagos', country: 'Nigeria' },
  { name: 'Lahore', country: 'Pakistan' },
  { name: 'Leon', country: 'Mexico' },
  { name: 'Lisbon', country: 'Portugal' },
  { name: 'London', country: 'United Kingdom' },
  { name: 'Long Beach', country: 'United States' },
  { name: 'Los Angeles', country: 'United States' },
  { name: 'Louisville', country: 'United States' },
  { name: 'Lucknow', country: 'India' },
  { name: 'Lyon', country: 'France' },
  // M
  { name: 'Madinah', country: 'Saudi Arabia' },
  { name: 'Madrid', country: 'Spain' },
  { name: 'Makkah', country: 'Saudi Arabia' },
  { name: 'Male', country: 'Maldives' },
  { name: 'Manchester', country: 'United Kingdom' },
  { name: 'Manila', country: 'Philippines' },
  { name: 'Marrakesh', country: 'Morocco' },
  { name: 'Mashhad', country: 'Iran' },
  { name: 'Mecca', country: 'Saudi Arabia' },
  { name: 'Medan', country: 'Indonesia' },
  { name: 'Melbourne', country: 'Australia' },
  { name: 'Mesa', country: 'United States' },
  { name: 'Mexico City', country: 'Mexico' },
  { name: 'Miami', country: 'United States' },
  { name: 'Milan', country: 'Italy' },
  { name: 'Minneapolis', country: 'United States' },
  { name: 'Mogadishu', country: 'Somalia' },
  { name: 'Monrovia', country: 'Liberia' },
  { name: 'Montreal', country: 'Canada' },
  { name: 'Moscow', country: 'Russia' },
  { name: 'Mosul', country: 'Iraq' },
  { name: 'Mumbai', country: 'India' },
  { name: 'Munich', country: 'Germany' },
  { name: 'Muscat', country: 'Oman' },
  // N
  { name: 'Nairobi', country: 'Kenya' },
  { name: 'Najaf', country: 'Iraq' },
  { name: 'Naples', country: 'Italy' },
  { name: 'Nashville', country: 'United States' },
  { name: 'New York', country: 'United States' },
  { name: 'Nice', country: 'France' },
  { name: 'Nicosia', country: 'Cyprus' },
  // O
  { name: 'Oklahoma City', country: 'United States' },
  { name: 'Omdurman', country: 'Sudan' },
  { name: 'Oran', country: 'Algeria' },
  { name: 'Orlando', country: 'United States' },
  { name: 'Osaka', country: 'Japan' },
  { name: 'Oslo', country: 'Norway' },
  { name: 'Ottawa', country: 'Canada' },
  // P
  { name: 'Paris', country: 'France' },
  { name: 'Peshawar', country: 'Pakistan' },
  { name: 'Philadelphia', country: 'United States' },
  { name: 'Phoenix', country: 'United States' },
  { name: 'Pittsburgh', country: 'United States' },
  { name: 'Portland', country: 'United States' },
  { name: 'Prague', country: 'Czech Republic' },
  { name: 'Pristina', country: 'Kosovo' },
  { name: 'Puebla', country: 'Mexico' },
  { name: 'Pune', country: 'India' },
  // Q
  { name: 'Quetta', country: 'Pakistan' },
  { name: 'Qom', country: 'Iran' },
  // R
  { name: 'Rabat', country: 'Morocco' },
  { name: 'Rawalpindi', country: 'Pakistan' },
  { name: 'Riyadh', country: 'Saudi Arabia' },
  { name: 'Rome', country: 'Italy' },
  { name: 'Rotterdam', country: 'Netherlands' },
  // S
  { name: 'Sacramento', country: 'United States' },
  { name: 'Sanaa', country: 'Yemen' },
  { name: 'San Antonio', country: 'United States' },
  { name: 'San Diego', country: 'United States' },
  { name: 'San Francisco', country: 'United States' },
  { name: 'San Jose', country: 'United States' },
  { name: 'Santiago', country: 'Chile' },
  { name: 'Sapporo', country: 'Japan' },
  { name: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { name: 'Seattle', country: 'United States' },
  { name: 'Seoul', country: 'South Korea' },
  { name: 'Shanghai', country: 'China' },
  { name: 'Sharjah', country: 'United Arab Emirates' },
  { name: 'Sfax', country: 'Tunisia' },
  { name: 'Shenzhen', country: 'China' },
  { name: 'Singapore', country: 'Singapore' },
  { name: 'Skopje', country: 'North Macedonia' },
  { name: 'Sofia', country: 'Bulgaria' },
  { name: 'Srinagar', country: 'India' },
  { name: 'Stockholm', country: 'Sweden' },
  { name: 'Surabaya', country: 'Indonesia' },
  { name: 'Sydney', country: 'Australia' },
  // T
  { name: 'Tabriz', country: 'Iran' },
  { name: 'Taiz', country: 'Yemen' },
  { name: 'Tashkent', country: 'Uzbekistan' },
  { name: 'Tbilisi', country: 'Georgia' },
  { name: 'Tehran', country: 'Iran' },
  { name: 'The Hague', country: 'Netherlands' },
  { name: 'Thimphu', country: 'Bhutan' },
  { name: 'Tijuana', country: 'Mexico' },
  { name: 'Tirana', country: 'Albania' },
  { name: 'Tokyo', country: 'Japan' },
  { name: 'Toronto', country: 'Canada' },
  { name: 'Tripoli', country: 'Libya' },
  { name: 'Tunis', country: 'Tunisia' },
  { name: 'Turin', country: 'Italy' },
  // U
  { name: 'Vancouver', country: 'Canada' },
  { name: 'Vienna', country: 'Austria' },
  // W
  { name: 'Wah', country: 'Pakistan' },
  { name: 'Warsaw', country: 'Poland' },
  { name: 'Wellington', country: 'New Zealand' },
  // X
  { name: "Xi'an", country: 'China' },
  // Y
  { name: 'Yokohama', country: 'Japan' },
  // Z
  { name: 'Zagreb', country: 'Croatia' },
  { name: 'Zanzibar', country: 'Tanzania' },
  { name: 'Zurich', country: 'Switzerland' },
];